# docker/docker-compose.yml
version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: fastapi_web
    ports:
      - "8000:8000"
    networks:
      - app-network
    depends_on:
      - redis
      - postgres
    environment:
      - DATABASE_URL=postgresql://postgres:password@postgres/dbname
      - REDIS_URL=redis://redis:6379

  redis:
    image: redis:7
    container_name: redis
    networks:
      - app-network
    ports:
      - "6379:6379"

  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: dbname
    networks:
      - app-network
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data: